--------------------------------------------------------
--  파일이 생성됨 - 목요일-8월-25-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BUY
--------------------------------------------------------

  CREATE TABLE "BOOK"."BUY" 
   (	"B_NO" NUMBER(10,0), 
	"M_ID" NVARCHAR2(50), 
	"B_NAME" NVARCHAR2(100), 
	"B_PHONE" NVARCHAR2(100), 
	"B_RECEIVE" NVARCHAR2(100), 
	"B_PRICE" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CART
--------------------------------------------------------

  CREATE TABLE "BOOK"."CART" 
   (	"M_ID" NVARCHAR2(50), 
	"G_NO" VARCHAR2(20 BYTE), 
	"G_NAME" VARCHAR2(100 BYTE), 
	"G_PUB" VARCHAR2(100 BYTE), 
	"G_PRICE" NUMBER(8,0), 
	"CL_QTY" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table GOODS
--------------------------------------------------------

  CREATE TABLE "BOOK"."GOODS" 
   (	"G_NO" VARCHAR2(20 BYTE), 
	"G_NAME" VARCHAR2(100 BYTE), 
	"G_PUB" VARCHAR2(100 BYTE), 
	"G_PRICE" NUMBER(8,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table INQUIRY
--------------------------------------------------------

  CREATE TABLE "BOOK"."INQUIRY" 
   (	"BR_NO" NUMBER, 
	"BR_ID" NVARCHAR2(50), 
	"BR_PW" NVARCHAR2(50), 
	"BR_CONT" NVARCHAR2(1000), 
	"BR_DATE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE "BOOK"."MEMBER" 
   (	"M_ID" NVARCHAR2(50), 
	"M_PW" NVARCHAR2(50), 
	"M_NAME" NVARCHAR2(50), 
	"M_JOOMIN" NVARCHAR2(15), 
	"M_ADDRESS" NVARCHAR2(100), 
	"M_PHONE" NVARCHAR2(15)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PAY
--------------------------------------------------------

  CREATE TABLE "BOOK"."PAY" 
   (	"M_ID" NVARCHAR2(50), 
	"P_DEP" NVARCHAR2(50), 
	"P_NO" NVARCHAR2(100), 
	"P_MONTH" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into BOOK.BUY
SET DEFINE OFF;
REM INSERTING into BOOK.CART
SET DEFINE OFF;
REM INSERTING into BOOK.GOODS
SET DEFINE OFF;
Insert into BOOK.GOODS (G_NO,G_NAME,G_PUB,G_PRICE) values ('2201','자바스크립트 웹 표준의 정석','이지스퍼블리싱',30000);
Insert into BOOK.GOODS (G_NO,G_NAME,G_PUB,G_PRICE) values ('2202','조코딩의 프로그래밍 입문','이지스퍼블리싱',18000);
Insert into BOOK.GOODS (G_NO,G_NAME,G_PUB,G_PRICE) values ('2203','쉽게 배우는 파이썬 데이터 분석','ITBOOK',23000);
Insert into BOOK.GOODS (G_NO,G_NAME,G_PUB,G_PRICE) values ('2204','알고리즘 코딩 테스트','ITBOOK',32000);
Insert into BOOK.GOODS (G_NO,G_NAME,G_PUB,G_PRICE) values ('2205','비전공자를 위한 이해할 수 있는 IT지식','TWIG',17000);
Insert into BOOK.GOODS (G_NO,G_NAME,G_PUB,G_PRICE) values ('2206','여행자','웅진지식하우스',17500);
Insert into BOOK.GOODS (G_NO,G_NAME,G_PUB,G_PRICE) values ('2207','알고 있다는 착각','세일즈포인트',18000);
Insert into BOOK.GOODS (G_NO,G_NAME,G_PUB,G_PRICE) values ('2208','우리는 어디서 살아야 하는가','세일즈포인트',20000);
Insert into BOOK.GOODS (G_NO,G_NAME,G_PUB,G_PRICE) values ('2209','역사상 가장 위대한 경제이론','역사비평사',16500);
Insert into BOOK.GOODS (G_NO,G_NAME,G_PUB,G_PRICE) values ('2210','한국 경제의 설계자들','역사비평사',27000);
REM INSERTING into BOOK.INQUIRY
SET DEFINE OFF;
REM INSERTING into BOOK.MEMBER
SET DEFINE OFF;
Insert into BOOK.MEMBER (M_ID,M_PW,M_NAME,M_JOOMIN,M_ADDRESS,M_PHONE) values ('temp','temppw','홍길동','991111','서울시 강남구 논현동','010-1111-1111');
Insert into BOOK.MEMBER (M_ID,M_PW,M_NAME,M_JOOMIN,M_ADDRESS,M_PHONE) values ('temp2','temp2pw','김유신','891122','경기도 용인시 수지구','010-2222-2222');
Insert into BOOK.MEMBER (M_ID,M_PW,M_NAME,M_JOOMIN,M_ADDRESS,M_PHONE) values ('안녕하세요','안녕123','김연아','900905','서울시 송파구','010-1234-1234');
Insert into BOOK.MEMBER (M_ID,M_PW,M_NAME,M_JOOMIN,M_ADDRESS,M_PHONE) values ('system','systempw','관리자','해당없음','해당없음','해당없음');
REM INSERTING into BOOK.PAY
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index MG_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOOK"."MG_PK" ON "BOOK"."CART" ("M_ID", "G_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007204
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOOK"."SYS_C007204" ON "BOOK"."GOODS" ("G_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007210
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOOK"."SYS_C007210" ON "BOOK"."MEMBER" ("M_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007222
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOOK"."SYS_C007222" ON "BOOK"."BUY" ("B_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007226
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOOK"."SYS_C007226" ON "BOOK"."PAY" ("M_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007227
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOOK"."SYS_C007227" ON "BOOK"."PAY" ("P_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007231
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOOK"."SYS_C007231" ON "BOOK"."INQUIRY" ("BR_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007222
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOOK"."SYS_C007222" ON "BOOK"."BUY" ("B_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MG_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOOK"."MG_PK" ON "BOOK"."CART" ("M_ID", "G_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007204
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOOK"."SYS_C007204" ON "BOOK"."GOODS" ("G_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007231
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOOK"."SYS_C007231" ON "BOOK"."INQUIRY" ("BR_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007210
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOOK"."SYS_C007210" ON "BOOK"."MEMBER" ("M_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007226
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOOK"."SYS_C007226" ON "BOOK"."PAY" ("M_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007227
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOOK"."SYS_C007227" ON "BOOK"."PAY" ("P_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table BUY
--------------------------------------------------------

  ALTER TABLE "BOOK"."BUY" ADD PRIMARY KEY ("B_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BOOK"."BUY" MODIFY ("B_PRICE" NOT NULL ENABLE);
  ALTER TABLE "BOOK"."BUY" MODIFY ("B_RECEIVE" NOT NULL ENABLE);
  ALTER TABLE "BOOK"."BUY" MODIFY ("B_PHONE" NOT NULL ENABLE);
  ALTER TABLE "BOOK"."BUY" MODIFY ("B_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CART
--------------------------------------------------------

  ALTER TABLE "BOOK"."CART" ADD CONSTRAINT "MG_PK" PRIMARY KEY ("M_ID", "G_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BOOK"."CART" MODIFY ("CL_QTY" NOT NULL ENABLE);
  ALTER TABLE "BOOK"."CART" MODIFY ("G_PRICE" NOT NULL ENABLE);
  ALTER TABLE "BOOK"."CART" MODIFY ("G_PUB" NOT NULL ENABLE);
  ALTER TABLE "BOOK"."CART" MODIFY ("G_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GOODS
--------------------------------------------------------

  ALTER TABLE "BOOK"."GOODS" ADD PRIMARY KEY ("G_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BOOK"."GOODS" MODIFY ("G_PRICE" NOT NULL ENABLE);
  ALTER TABLE "BOOK"."GOODS" MODIFY ("G_PUB" NOT NULL ENABLE);
  ALTER TABLE "BOOK"."GOODS" MODIFY ("G_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table INQUIRY
--------------------------------------------------------

  ALTER TABLE "BOOK"."INQUIRY" ADD PRIMARY KEY ("BR_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BOOK"."INQUIRY" MODIFY ("BR_PW" NOT NULL ENABLE);
  ALTER TABLE "BOOK"."INQUIRY" MODIFY ("BR_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "BOOK"."MEMBER" ADD PRIMARY KEY ("M_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BOOK"."MEMBER" MODIFY ("M_PHONE" NOT NULL ENABLE);
  ALTER TABLE "BOOK"."MEMBER" MODIFY ("M_ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "BOOK"."MEMBER" MODIFY ("M_JOOMIN" NOT NULL ENABLE);
  ALTER TABLE "BOOK"."MEMBER" MODIFY ("M_NAME" NOT NULL ENABLE);
  ALTER TABLE "BOOK"."MEMBER" MODIFY ("M_PW" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PAY
--------------------------------------------------------

  ALTER TABLE "BOOK"."PAY" ADD UNIQUE ("P_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BOOK"."PAY" ADD PRIMARY KEY ("M_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BOOK"."PAY" MODIFY ("P_MONTH" NOT NULL ENABLE);
  ALTER TABLE "BOOK"."PAY" MODIFY ("P_DEP" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table BUY
--------------------------------------------------------

  ALTER TABLE "BOOK"."BUY" ADD CONSTRAINT "BUY_DELETE" FOREIGN KEY ("M_ID")
	  REFERENCES "BOOK"."MEMBER" ("M_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CART
--------------------------------------------------------

  ALTER TABLE "BOOK"."CART" ADD CONSTRAINT "G_NO_FK" FOREIGN KEY ("G_NO")
	  REFERENCES "BOOK"."GOODS" ("G_NO") ON DELETE CASCADE ENABLE;
  ALTER TABLE "BOOK"."CART" ADD CONSTRAINT "M_ID_FK" FOREIGN KEY ("M_ID")
	  REFERENCES "BOOK"."MEMBER" ("M_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table INQUIRY
--------------------------------------------------------

  ALTER TABLE "BOOK"."INQUIRY" ADD CONSTRAINT "INQUIRY_DELETE" FOREIGN KEY ("BR_ID")
	  REFERENCES "BOOK"."MEMBER" ("M_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PAY
--------------------------------------------------------

  ALTER TABLE "BOOK"."PAY" ADD CONSTRAINT "PAY_DELETE" FOREIGN KEY ("M_ID")
	  REFERENCES "BOOK"."MEMBER" ("M_ID") ON DELETE CASCADE ENABLE;
